[package]
name = "todo"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.16", features = ["derive"] }
dirs = "5.0.1"
reedline = "0.38.0"
rusqlite = { version = "0.32.1", features = ["bundled"] }
shlex = "1.3.0"
thiserror = "2.0.9"
